Repository dashpay/platform, pull requests merged in 2025-04, with the labels that each got.

#2541 fix(dpp): missing closing bracket in validate contract update
  packages/rs-dpp/src/data_contract/methods/validate_update/v0/mod.rs
Labels: bug

#2478 feat(platform): transfer to frozen account is allowed
  packages/rs-dpp/src/data_contract/associated_token/token_configuration/accessors/mod.rs
  packages/rs-dpp/src/data_contract/associated_token/token_configuration/accessors/v0/mod.rs
  packages/rs-dpp/src/data_contract/associated_token/token_configuration/v0/accessors.rs
  packages/rs-dpp/src/data_contract/associated_token/token_configuration/v0/mod.rs
  packages/rs-drive-abci/src/execution/platform_events/initialization/create_genesis_state/test/tokens.rs
  packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/batch/action_validation/token/token_mint_transition_action/state_v0/mod.rs
  packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/batch/action_validation/token/token_transfer_transition_action/state_v0/mod.rs
  packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/batch/tests/token/mod.rs
  packages/rs-drive-abci/tests/strategy_tests/token_tests.rs
Labels: leftover

#2580 fix(sdk): compare underlying returned data on proof verification
  packages/rs-dpp/src/document/document_methods/is_equal_ignoring_timestamps/v0/mod.rs
  packages/rs-drive/src/verify/state_transition/verify_state_transition_was_executed_with_proof/v0/mod.rs
  packages/rs-platform-value/src/btreemap_extensions/equal_underlying_data.rs
  packages/rs-platform-value/src/btreemap_extensions/mod.rs
  packages/rs-platform-value/src/eq.rs
  packages/rs-platform-value/src/lib.rs
Labels: rs-sdk
