Repository dashpay/platform, pull requests merged in 2025-01, with the labels that each got.

#2416 test: unify identity versioned cost coverage
  packages/rs-drive/src/drive/document/insert/mod.rs
  packages/rs-drive/src/drive/identity/balance/update.rs
  packages/rs-drive/src/drive/identity/insert/add_new_identity/mod.rs
  packages/rs-drive/src/drive/identity/insert/add_new_identity/v0/mod.rs
  packages/rs-drive/src/drive/identity/update/mod.rs
Labels: enhancement, cleanup

#2420 fix(drive-abci): document purchase on mutable document from different epoch had issue
  .github/actions/librocksdb/action.yaml
  Cargo.lock
  Dockerfile
  packages/rs-drive-abci/Cargo.toml
  packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/mod.rs
  packages/rs-drive-abci/tests/supporting_files/contract/crypto-card-game/crypto-card-game-direct-purchase-documents-mutable.json
  packages/rs-drive/Cargo.toml
  packages/rs-drive/src/drive/document/estimation_costs/stateless_delete_of_non_tree_for_costs/v0/mod.rs
  packages/rs-drive/src/util/grove_operations/mod.rs
  packages/rs-platform-version/Cargo.toml
  packages/strategy-tests/Cargo.toml
Labels: bug

#2401 feat(dpp): extra methods for state transitions in wasm
  packages/rs-dpp/src/state_transition/state_transitions/document/documents_batch_transition/document_transition/action_type.rs
  packages/rs-dpp/src/state_transition/state_transitions/document/documents_batch_transition/document_transition/mod.rs
  packages/wasm-dpp/src/data_contract/state_transition/data_contract_create_transition/mod.rs
  packages/wasm-dpp/src/data_contract/state_transition/data_contract_update_transition/mod.rs
  packages/wasm-dpp/src/document/state_transition/document_batch_transition/document_transition/document_create_transition.rs
  packages/wasm-dpp/src/document/state_transition/document_batch_transition/document_transition/document_delete_transition.rs
  packages/wasm-dpp/src/document/state_transition/document_batch_transition/document_transition/document_replace_transition.rs
  packages/wasm-dpp/src/document/state_transition/document_batch_transition/document_transition/mod.rs
  packages/wasm-dpp/src/document/state_transition/document_batch_transition/mod.rs
  packages/wasm-dpp/src/identity/state_transition/identity_create_transition/identity_create_transition.rs
  packages/wasm-dpp/src/identity/state_transition/identity_credit_transfer_transition/transition.rs
  packages/wasm-dpp/src/identity/state_transition/identity_credit_withdrawal_transition/transition.rs
  packages/wasm-dpp/src/identity/state_transition/identity_topup_transition/identity_topup_transition.rs
  packages/wasm-dpp/src/identity/state_transition/identity_update_transition/identity_update_transition.rs
  packages/wasm-dpp/src/voting/state_transition/masternode_vote_transition/mod.rs
Labels: js-sdk
